services:
  db:
    image: postgres:16-alpine
    container_name: school_portal_db
    restart: always
    environment:
      POSTGRES_DB: schoolportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: